version: 2.1

jobs:
 build:
   machine: true
   steps:
     - checkout
     #- run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
     - run: docker build -f Docker/app.deploy.Dockerfile -t inflection/service-geo:$CIRCLE_BRANCH .
     #- run: docker push inflection/service-geo:$CIRCLE_BRANCH
