version: '3.4'

services:

  service.geo:
    image: service.geo
    build:
      context: ..
      dockerfile: ./Docker/app.compose.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=DevelopmentDocker
    ports:
      - "6003:80"
    depends_on:
      - data.sql.geo

  data.sql.geo:
    image: data.sql.geo
    build:
      context: .
      dockerfile: db.compose.Dockerfile
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
